[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/pay"
  to = "/.netlify/functions/pay"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200